// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_products_default = defineTool({
  name: "list_products",
  title: "List JBLinx Studio products",
  description: "List JBLinx Studio's flagship products with a short description and category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const products = [
      { name: "CodeFusion Studio", category: "Development", description: "Browser-based IDE for building web apps." },
      { name: "CodeCraftAI Pro", category: "Development", description: "AI-powered coding assistant." },
      { name: "VitalitySync", category: "Health Tech", description: "Wellness and habit tracking app." },
      { name: "MindMate", category: "Gaming", description: "Strategy games and puzzle hub." },
      { name: "NestCore", category: "PropTech", description: "Real estate management platform." }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List JBLinx Studio services",
  description: "List the services JBLinx Studio offers to clients.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = [
      { name: "Game Development", description: "Custom game development across Unity and web platforms." },
      { name: "Web Applications", description: "Modern full-stack web apps with React, TypeScript, and backend APIs." },
      { name: "Backend & APIs", description: "Production-ready backend APIs, databases, and DevOps." },
      { name: "Developer Tools", description: "Open-source templates, CLIs, and component libraries." }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/tools/get-studio-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_studio_info_default = defineTool3({
  name: "get_studio_info",
  title: "Get JBLinx Studio info",
  description: "Get an overview of JBLinx Studio: what it does, focus areas, and how to get in touch.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "JBLinx Studio",
      tagline: "Premium development studio building products, games, and developer tools.",
      focusAreas: ["Web Applications", "Game Development", "Health Tech", "PropTech", "Developer Tools"],
      github: "https://github.com/JBLinx-Studio",
      contact: "Visit the site's Support page to get in touch."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jblinx-studio-mcp",
  title: "JBLinx Studio MCP",
  version: "0.1.0",
  instructions: "Tools for exploring JBLinx Studio's public catalog: products, services, and studio info. All data returned is public.",
  tools: [list_products_default, list_services_default, get_studio_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
